### ISSUE TITLE
[REQUEST] Clear screen while exit bashtop

### ISSUE THREAD

**Issue by MarkusNeviadomski** [aristocratos/bashtop#101]
When i quit the program, i want to have a cleared screen ( like running clear).

**Comment by aristocratos** [comment]
Why?

The screen when starting bashtop is saved `tput smcup` and restored when quitting `tput rmcup`.
Seems pretty pointless to clear the screen after restoring the screen you had before starting bashtop.

Solution if you really want to clear after having run, put `alias bashtop='bashtop; clear` in your `.bashrc`, `.zshrc` or whatever shell config you have.

**Comment by MarkusNeviadomski** [comment]
No, session is not saved and restored when running in screen. tput does not work there
![image](https://user-images.githubusercontent.com/6367277/81082056-0462c380-8ef3-11ea-80e7-70d37d74bbe4.png)

**Comment by aristocratos** [comment]
Follow the [#Compatibility](https://github.com/aristocratos/bashtop#compatibility) guidelines for correctly showing bashtop.

I will not replace a feature because it's not working outside the frame of where it's supposed to work.

To get the result you are looking for under current conditions, use the solution provided above.

**Comment by aristocratos** [comment]
`tput` works fine for me running screen, except not being 24-bit color.

**Comment by MarkusNeviadomski** [comment]
@aristocratos Maybe you can send me your screen config? I have no real special config in my screen, so i am little confused that it works at your end with screen.

This is my one: 
bindkey -k F1 prev
bindkey -k F2 next
hardstatus string "$USER@%H %{kg} Load: %l %{wr} %c %{wb} %n %t %{kw} %W "
hardstatus alwayslastline
screen 0
screen 1
screen 2

**Comment by aristocratos** [comment]
@MarkusNeviadomski Turns out it was actually zsh that automatically cleaned up anything below the prompt when I ran through `screen`. So does seem like `tput` at least can't save and restore when running through `screen`. It does however work great with full 24-bit color support in `tmux`. So I would recommend switching to `tmux` if you want bashtop to behave as it should.

**Comment by MarkusNeviadomski** [comment]
Thanks @aristocratos  for investigation. I'm not shut if tmux is a valide alternative to screen for me, but good to know. It's like vim or emacs i thought.
