### ISSUE TITLE
Cohesive Colorscheme [REQUEST]

### ISSUE THREAD

**Issue by patillacode** [aristocratos/bashtop#11]
**Is your feature request related to a problem? Please describe.**
Default colors could not match a user's color setup

**Describe the solution you'd like**
I would suggest trying to set the used colors based on a user's `.Xresources` file and if not, then fallback to the current colorscheme

**Describe alternatives you've considered**
None

**Additional context**
Hi @aristocratos 

I wanted to say I think this is a very nice and fancy tool and I really like it.
I noticed you had this item on your TODO list I just thought I would give you an idea to consider in order to achieve it.

I could potentially come up with a PR if I can find some time, but in the meantime I just wanted to raise this as a feature request.

Thanks!

**Comment by aristocratos** [comment]
Hi, I'm currently working on rewriting how the arrays that hold colors for graphs and meters are made, from static to a dynamic function. I was thinking of implementing theme files, since there's gonna be alot of variables for setting 24bit rgb colors; gradient start, middle and end for graphs and gradient start and end for meters and then text colors and colors for the boxes.

I don't know if pulling colors from .Xresources would be practical without defined values for bashtop, but possibly get theme name from there if that would be helpful?

**Comment by patillacode** [comment]
I see, it makes sense to follow that path, I think it is a great idea.|

I was thinking of a mid-term solution, in case this wasn't in current development) just to try to _guess_ what colors to put based on an existing scheme (`.Xresources`)

The way you mention you are implementing this seems like a much better approach.

Thanks again
