### ISSUE TITLE
[REQUEST] Theme - Nord

### ISSUE THREAD

**Issue by Justinzobel** [aristocratos/bashtop#116]
**Is your feature request related to a problem? Please describe.**
New theme based on Nord Palette https://www.nordtheme.com

**Describe the solution you'd like**
Addition of new theme

Palette here: 

**Additional context**
Initial theme (likely needs a bit more tweaking):
![image](https://user-images.githubusercontent.com/1370117/82006359-c3af3b00-96a6-11ea-923b-568fe028fa36.png)

nord.theme file:
```
#Bashtop theme with nord palette (https://www.nordtheme.com)
#by Justin Zobel <justin.zobel@gmail.com>

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#2E3440"

# Main text color
theme[main_fg]="#E5E9F0"

# Title color for boxes
theme[title]="#"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#434c5e"

# Background color of selected item in processes box
theme[selected_bg]="#4C566A"

# Foreground color of selected item in processes box
theme[selected_fg]="#ECEFF4"

# Color of inactive/disabled text
theme[inactive_fg]="#4C566A"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#367bf0"

# Cpu box outline color
theme[cpu_box]="#d8dee9"

# Memory/disks box outline color
theme[mem_box]="#d8dee9"

# Net up/down box outline color
theme[net_box]="#d8dee9"

# Processes box outline color
theme[proc_box]="#d8dee9"

# Box divider line and small boxes line color
theme[div_line]="#d8dee9"

# Temperature graph colors
theme[temp_start]="#4c566a"
theme[temp_mid]="#434c5e"
theme[temp_end]="#3b4252"

# CPU graph colors
theme[cpu_start]="#3b4252"
theme[cpu_mid]="#434c5e"
theme[cpu_end]="#4c566a"

# Mem/Disk free meter
theme[free_start]="#3b4252"
theme[free_mid]="#434c5e"
theme[free_end]="#4c566a"

# Mem/Disk cached meter
theme[cached_start]="#3b4252"
theme[cached_mid]="#434c5e"
theme[cached_end]="#4c566a"

# Mem/Disk available meter
theme[available_start]="#3b4252"
theme[available_mid]="#434c5e"
theme[available_end]="#4c566a"

# Mem/Disk used meter
theme[used_start]="#3b4252"
theme[used_mid]="#434c5e"
theme[used_end]="#4c566a"

# Download graph colors
theme[download_start]="#3b4252"
theme[download_mid]="#434c5e"
theme[download_end]="#4c566a"

# Upload graph colors
theme[upload_start]="#3b4252"
theme[upload_mid]="#434c5e"
theme[upload_end]="#4c566a"
```

**Comment by aristocratos** [comment]
The error with some text elements is because of
``` bash
# Title color for boxes
theme[title]="#"
```
Needs to be either completely empty for default value or have a color value. Right now it inserts the `#` in front of text that uses "title" colors, because of me being lazy and not adding error checking to the theme parsing.

And the gradients are a bit to close to each other, since it tries to calculate 50 color values between each of the three color values. And again me not implementing error checking in the theme parsing results in broken gradients when failing to generate all values.

If anyone wanna fix and test the theme I'll add it to the repository. Otherwise I'll do it when I have some spare time.

**Comment by Justinzobel** [comment]
Awesome I'll try make tweaks tomorrow and update.

**Comment by Justinzobel** [comment]
Thoughts on this?
![image](https://user-images.githubusercontent.com/1370117/82108709-8793dd00-976f-11ea-9b82-525815d1322d.png)

**Comment by aristocratos** [comment]
Released v0.8.31 with some changes to theme parsing, should make it easier to create two color gradients.
When you're happy with the look of the theme, make pull request with the theme added to the theme folder or post the complete theme here and will add it.

**Comment by Justinzobel** [comment]
Thoughts? Have updated to 0.9.6 and adjusted theme:
![image](https://user-images.githubusercontent.com/1370117/83084853-513c5300-a0c9-11ea-9739-3d59e3914480.png)

**Comment by gwarf** [comment]
It's quite nice, hard for me to comment on how well it complies with the nord recommendations but I would say that it would probably be great enough for a first inclusion in the main repo, and if needed it can be amended later :)

Well done!

**Comment by aristocratos** [comment]
I actually liked the first version with more of an white on blue feel to it, but that's just my opinion.
It's your theme, so let me know when YOU are happy with the look and I will add it :)
All is good as long as all text elements is readable and there aren't any errors in the theme file.

It's however a problematic to change the theme later, since the builtin theme downloader doesn't overwrite any existing themes. So would only update if you manually removed the theme first.
You could however create multiple versions with different names in that case.

**Comment by gwarf** [comment]
I wonder if @arcticicestudio would be able to provide some feedback, would be great! :)

(Would you mind updating the PR title so that it's easier to find in the PR list?)

**Comment by Justinzobel** [comment]
Not sure where that title came from. I'd also love to get feedback from the Nord team. I just chose colours that I thought would look good but they're the true masters of colour matching.

**Comment by arcticicestudio** [comment]
I also found this great project through my GitHub dashboard/feed and added it to my never ending TODO list to the "create official Nord port for this" section 😄 

The last screenshot already looks quite nice. I haven't checked the theming API yet, but if it's possible some common text elements could use `nord4` as foreground color to make it easier to spot more important information at a glance. Otherwise I'd say it matches Nord's style, but a PR would be great to review the code together.

There's one concern left:

> It's however a problematic to change the theme later, since the builtin theme downloader doesn't overwrite any existing themes.

This would mean the _Nord_ theme is kind of “locked“, only allowing to change it by adding a new file so e.g. fixing a bug/visual regression requires a kind of meaningless name for a almost 100% identical copy of the original theme file. This also applies to changes to the theme API like mentioned above. So after more than 2 or 3 theme updates user will be confused which is actually the latest version of a theme.
This is also a blocker for me to help to maintain the theme for _Bashtop_ and also prevents a possible "official" port project since the theme cannot be updated properly or customized/installed by the user at all.

In my opinion this sounds like a architectural problem that should be resolved before merging any new theme. One solution might be to…

1. …always **override theme files** that are **located in the reserved path of _Bashtop_** — these files are provided by this project and users should not place custom theme files in the application specific directories. This way ensures that updates to themes in the repository are always reflected on the user system.
2. …look up **user-level paths for custom themes** — _Bashtop_ should look up for custom themes placed by the user in a user-level directory, preferably following the [XDG directory specification][xdg] (e.g. `$HOME/.local/share/bashtop/themes`). When a theme file with the same name is found it'll take precedence over _Bashtop_'s provided themes.

This is kind of a standard way to resolve such problems that helps to prevent conflicts with updates and user customizations.

I know this goes beyond the topic in this issue, but I was a bit worried about this little fact.

[xdg]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Justinzobel** [comment]
I updated 
"Main text color":
theme[main_fg]="#D8DEE9"
to `Nord4` I think, I was a bit confused by the naming scheme I hope that's the right hex ID.

![image](https://user-images.githubusercontent.com/1370117/83847495-8260f700-a74b-11ea-999e-7114524c0cdb.png)

This is the full theme you can place in `~/.config/bashtop/themes` as `nord.theme`:
```
#Bashtop theme with nord palette (https://www.nordtheme.com)
#by Justin Zobel <justin.zobel@gmail.com>

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#2E3440"

# Main text color
theme[main_fg]="#D8DEE9"

# Title color for boxes
theme[title]="#8FBCBB"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#5E81AC"

# Background color of selected item in processes box
theme[selected_bg]="#4C566A"

# Foreground color of selected item in processes box
theme[selected_fg]="#ECEFF4"

# Color of inactive/disabled text
theme[inactive_fg]="#4C566A"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#5E81AC"

# Cpu box outline color
theme[cpu_box]="#4C566A"

# Memory/disks box outline color
theme[mem_box]="#4C566A"

# Net up/down box outline color
theme[net_box]="#4C566A"

# Processes box outline color
theme[proc_box]="#4C566A"

# Box divider line and small boxes line color
theme[div_line]="#4C566A"

# Temperature graph colors
theme[temp_start]="#81A1C1"
theme[temp_mid]="#88C0D0"
theme[temp_end]="#ECEFF4"

# CPU graph colors
theme[cpu_start]="#81A1C1"
theme[cpu_mid]="#88C0D0"
theme[cpu_end]="#ECEFF4"

# Mem/Disk free meter
theme[free_start]="#81A1C1"
theme[free_mid]="#88C0D0"
theme[free_end]="#ECEFF4"

# Mem/Disk cached meter
theme[cached_start]="#81A1C1"
theme[cached_mid]="#88C0D0"
theme[cached_end]="#ECEFF4"

# Mem/Disk available meter
theme[available_start]="#81A1C1"
theme[available_mid]="#88C0D0"
theme[available_end]="#ECEFF4"

# Mem/Disk used meter
theme[used_start]="#81A1C1"
theme[used_mid]="#88C0D0"
theme[used_end]="#ECEFF4"

# Download graph colors
theme[download_start]="#81A1C1"
theme[download_mid]="#88C0D0"
theme[download_end]="#ECEFF4"

# Upload graph colors
theme[upload_start]="#81A1C1"
theme[upload_mid]="#88C0D0"
theme[upload_end]="#ECEFF4"
```

Feel free to tweak as you see fit @arcticicestudio and submit as a PR.

**Comment by gwarf** [comment]
This one is more contrasted and it helps differentiate various kind of information, cool! 

And thanks @arcticicestudio for joining, had a similar reaction with regards non-updated theme files, the project/user theme model could be nice indeed :)

**Comment by aristocratos** [comment]
@arcticicestudio makes some very good points! And thanks for joining in the conversation :)

I'm gonna change the builtin theme downloader to overwrite themes in `.config/bashtop/themes`  and add `.config/bashtop/user_themes` that will override any default theme and be safe from overwrites.
The bashtop config folder already follow XDG specs if available so shouldn't be any issues there.

The theme downloader is still manually triggered from the options menu, so will add warnings and a notice about the `user_themes` folder in the menu description.

Anybody have any thoughts on this before I make any changes?

**Comment by arcticicestudio** [comment]
@Justinzobel This looks great 👍
It's not that monotone with one foreground color and makes it easier to distinguish headings from actual content.

@aristocratos LGTM 🚀

**Comment by Justinzobel** [comment]
Thanks I'll get a PR sorted momentarily.
