### ISSUE TITLE
How to identify which process misbehaved?

### ISSUE THREAD

**Issue by anishmittal2020** [aristocratos/bashtop#132]
In the following picture we can see on the top left graph that some process(s) consumed a lot of CPU a few seconds ago.

![image](https://user-images.githubusercontent.com/42092626/83736398-dedfeb80-a651-11ea-8f45-fffced993760.png)

I am facing this problem in a cyclic manner. How can I identify what process(s) consumed a lot of CPU suddenly? For example it would be useful to have a log at every second of processes that consume more than 25% of CPU (for each core) and  (or) 25% of Available memory .

**Comment by aristocratos** [comment]
Such a log would very quickly get very big and if written to disk for example would be very costly in cpu usage since this is bash. Could possibly work some profiling tools in to the python port.

By sorting processes by "cpu lazy" should give a pretty good view of what processes has been using most cpu in the last minute or so if it's a relatively new process.

But to accurately and verbosly log all processes I would recommend you find a tool made for that purpose.

Bashtop in it's current form is made for getting a snapshot of current resource use in a fancy manner, the history of usage doesn't reach farther than the general graphs.
