### ISSUE TITLE
[REQUEST] Change layout

### ISSUE THREAD

**Issue by turkeyphant** [aristocratos/bashtop#177]
**Is your feature request related to a problem? Please describe.**
I have 32 cores. I'm always frustrated when I can only see some of them yet there's acres of space for the disks and processes section (even though half the processes are too dark to be readable).

(related: maybe not have as strong a fade on the processes?)

**Describe the solution you'd like**
Some way of customising how much vertical space given to each element.

Failing that a way to stop elements being truncated.

**Describe alternatives you've considered**
Buying a higher res monitor.

**Additional context**
![image](https://user-images.githubusercontent.com/8129583/88348453-59b9ae80-cd45-11ea-931b-8f56803762fa.png)

**Comment by aristocratos** [comment]
Well you can turn off the gradient fade on the processes in the options.

Regarding truncating I would say wait for bpytop the python port of bashtop I've been working on the last month. I will be released in about a week. It got better scalability for the cores, full mouse support, uses barely a third of bashtops cpu consumption and has a lot more new features and options.

Right now I'm focusing on finishing bpytop and the only work I've been doing on bashtop is bug fixes.

It's possible I'll work in manual resizing of the boxes in bpytop, but it's a lot of work since I'm not using any outside libraries for the UI, so it's not a priority right now.

**Comment by turkeyphant** [comment]
The fade is nice just a bit rpemature/extreme.

But understand what you're saying and fair enough.
