### ISSUE TITLE
[BUG] Input lag

### ISSUE THREAD

**Issue by rahilwazir** [aristocratos/bashtop#36]
**Describe the bug**
When using arrow keys to navigating the processes there is a small delay. When viewing info for a process the delay is increased.

**To Reproduce**
Simply clone and run `bashtop`

**Info:**
 - Fedora 31, Linux 5.5.16-200.fc31.x86_64
 - Bash version 5.0.11

**Additional context**

Using default config and no errors.

**Comment by aristocratos** [comment]
This is not a bug but the reality of bash and a single threaded script. It depends heavily on the cpu it's being run on. But if anyone have any ideas for fixes without increasing cpu usage alot, let me know.

**Comment by aristocratos** [comment]
To give some more information, all input gets halted on calls to "ps", "df", "sensors" and so on. The biggest slowdown is "ps". There are ways to get around it, for example running the commands in background and redirecting the output to files. But that creates other problems, especially if "/dev/shm" isn't available and we have to write a lot to disk at every update.
In the testing I did, the added cpu usage didn't feel worth it to get rid of around occasional 100ms lag.

**Comment by drazil100** [comment]
Just thought of a great way you could reduce input lag (that doesn't even involve my idea of processing multiple keys at once mentioned in #84 

What you could do is implement a timer that gets set every time someone pushes a key that pauses the updating and filtering of items your proc list. Since the proc list is one of the heaviest parts of the program selectively not running ps and whatever you use to filter until maybe a second after the user has not typed anything would greatly improve the feel of responsiveness. In fact anything that is not a time-sensitive timelaps graph could be reasonably paused to get out of the way of the user.

**Comment by aristocratos** [comment]
Have something of the sort already implemented, the processes only gets redrawn (and not reprocessed) if moving within the list. But changing sorting or filtering needs new processing since all sorting except for "cpu responsive" is done by `ps` itself.

But good idea otherwise :)

**Comment by aristocratos** [comment]
There could be something to be done for the filter, but processing gets pretty negligible as the list shrinks in size.

**Comment by drazil100** [comment]
you could still implement a timer so that doesn't run ps until after about a second has passed after input to have it skip its regularly scheduled refreshes while the user is typing. 

Its honestly WAY smoother than it was when I first checked this project out but every so often while navigating the proc list bashtop will update the proc list and the cursor just stops for a quarter of a second. It really doesn't hurt the usability of bashtop but it is a noticeable stutter.

**Comment by drazil100** [comment]
As you can see it runs super smoothly on my system but once each page of the proc list while holding down the down key it stutters.

https://streamable.com/1u7r0x

**Comment by aristocratos** [comment]
Sure, but would only apply to up and down scrolling then. Was thinking of rewriting so the list actually scrolls instead of having pages, to make the tree view a little more usable. So would need to pause process updates while scrolling or it would be extremely slow.
