### ISSUE TITLE
Bashtop window doesn't resize in tmux[BUG]

### ISSUE THREAD

**Issue by s1q** [aristocratos/bashtop#70]
**Describe the bug**
Bashtop window doesn't resize in tmux, when I resizing tmux panes or resize terminal window

**To Reproduce**
1. launch tmux
2. split tmux window to two vertical panes
3. run bashtop in left pane
4. get message "Current size... Need to be atleast..."
5. Trying to resize panes with mouse or Ctrl+A - >
6. Sometimes bashtop doesn't react on pane resizing but in other apps it resize as good.

**Expected behavior**
Bashtop pane must resize normally

 - Linux distribution and version: Windows Ubuntu Subsystem
 - Bash version (version 4.4 or above is required): zsh 5.4.2

![image](https://user-images.githubusercontent.com/39670960/80527144-94a58380-899c-11ea-94c5-443cfb7b36a7.png)

**Comment by aristocratos** [comment]
> Bash version (version 4.4 or above is required): zsh 5.4.2

Should be bash version from `bash --version`

The terminal sized is collected with command `stty size` and updated every 500ms while resizing. If it fails to get correct size it's likely caused by either tmux, your terminal or both.

You can test it by running a `stty size` before and after splitting/resizing and see if it changes.
